### ISSUE TITLE
Include Map Legend

### ISSUE THREAD

**Issue by Renaud-Dov** [NathanCHEVALIER/epimap#1]
It would be cool to have the legend of the few icons, because i don't know what this logo means for example.
![image](https://user-images.githubusercontent.com/14821642/134822319-ea819f69-f050-4135-8b79-d688d27e3ca3.png)

**Comment by NathanCHEVALIER** [comment]
Great suggestion, a legend will be added in the next update.
Icons and fonts will also be updated in a more contemporary style, in order to facilitate the reading of the maps

**Comment by NathanCHEVALIER** [comment]
Finally, there were a few updates before the legend was added, but it's now time to close the first Epimap issue !

The legend is available (repo and online) by clicking on the three dots at the top right. Some icons like the one above have been removed from the maps to clarify them.
