### ISSUE TITLE
Update Villejuif VA Maps: THREAD

### ISSUE THREAD

**Issue by NathanCHEVALIER** [NathanCHEVALIER/epimap#27]
Leave a comment according to your progress/goal concerning:
map-vj-va-1.svg
map-vj-va0.svg
map-vj-va1.svg
map-vj-va2.svg
map-vj-va3.svg

**Comment by NathanCHEVALIER** [comment]
map-vj-va0.svg updated
Renamed to vj-va-f0.svg

**Comment by kolowy** [comment]
map vj-va-f0.svg updated with new standard style

map map-vj-va1.svg updated with new standard style
Renamed to vj-va-f1.svg

**Comment by NathanCHEVALIER** [comment]
vj-va-f2 updated and renammed

**Comment by NathanCHEVALIER** [comment]
vj-va-f3 updated and renamed
