### ISSUE TITLE
Update room at Villejuif - VA 311

### ISSUE THREAD

**Issue by Swarwerth** [NathanCHEVALIER/epimap#38]
The VA 311 has became a Machine Room (Salle Machine)
> https://epimap.fr/map-vj-va3

**Comment by NathanCHEVALIER** [comment]
This map has been updated 7 days ago and could be found here:
https://github.com/NathanCHEVALIER/epimap/blob/master/maps/vj-va-f3.svg

Difference between git and online version is dued to release time.

**Comment by NathanCHEVALIER** [comment]
A new release has been forced in order to update the online prod mirror. ([v.2022-09.1](https://github.com/NathanCHEVALIER/epimap/blob/master/docs/releases/2022-09.md))

The Villejuif A building 3rd floor direct link is now the following: 
> https://epimap.fr/vj-va-f3
