### ISSUE TITLE
Bug: don't work with dark reader

### ISSUE THREAD

**Issue by JulesdeCube** [NathanCHEVALIER/epimap#8]
## Issues

when using [dark reader](https://darkreader.org/help/fr/), the svg text don't change and the background become dark.

### Additional info

- firefox version 94.0
- linux nixos 21.11 unstable
- dark reader Version 4.9.42

## Step to reproduce

1. install firefox
2. install dark reader extension
3. enable dark reader
4. go to [epimal.fr](https://epimap.fr)

## Exemple

![image](https://user-images.githubusercontent.com/41579596/140990802-e41b200e-1b1c-481e-ad04-50a7ef62c88a.png)

**Comment by NathanCHEVALIER** [comment]
this problem comes from the same implementation mistake as issue #11 

It is due to the fact that the maps are embedded, which prevents to easily access to sub-document from the main document (here in order.

**Comment by NathanCHEVALIER** [comment]
Issue Solved with last major update (MR #14 )

![Captureepimap](https://user-images.githubusercontent.com/23084675/161934026-4f90d382-a3af-407a-8606-eb260e01538c.PNG)
